### PR TITLE
Server api version

### PR DESCRIPTION
**Pull request by andrewjamesbrown**
This PR adds initial support for versioned APIs in Chef Zero, as well as implements the /server_api_version endpoint.  The server-api-version test now passes as well.

### CODE REVIEW

**Comment by tyler-ball** [comment]
This looks awesome to me - thanks @andrewjamesbrown! :+1: 

Can we get someone from the @chef/server-team to review it?

**Comment by tyler-ball** [comment]
And just to clarify - this doesn't update all the APIs to respond to the different versions, it just adds the framework for doing receiving/responding.  Correct?

**Comment by andrewjamesbrown** [comment]
@tyler-ball, correct this simply adds the framework for doing receiving/responding.  Though it does add support for /server_api_version since it was pretty easy to add. :)

**Comment by randomcamel** [comment]
:+1:

**Pull request merged**
