### PR TITLE
Allow Hashie to float to 3.x (no need to be so specific)

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by tyler-ball** [comment]
What does this fix?  Multiple gems in the ChefDK?

**Comment by jkeiser** [comment]
@tyler-ball no, it lets me bring github_changelog_generator into our projects (because it wants hashie 3.0).

**Comment by jkeiser** [comment]
Others are having issues because of dependencies-of-dependencies as well. Just makes it more pleasant to work with projects.

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
