### PR TITLE
Skipping User Email case insensitive pedant test

### PR DESCRIPTION
**Pull request by jashaik**
Signed-off-by: jan shahid shaik <jashaik@progress.com>

## Description
 Chef Server is updated to support User Email case insensitive but chef-zero architecture is compatible to simulate this scenario.

## Related Issue

Chef Server is updated to support User Email case insensitive but chef-zero architecture is incompatible to simulate this scenario.Hence skipping the Email case insensitive pedant test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by PrajaktaPurohit — APPROVED** [review]
LGTM. I assume the pipeline failure is unrelated to this PR.

**Comment by marcparadise** [comment]
While the change looks OK, how much effort would it be to allow zero to support this usage? The goal for chef-zero is to maintain as much parity with server API as possible.

**Comment by jashaik** [comment]
> While the change looks OK, how much effort would it be to allow zero to support this usage? The goal for chef-zero is to maintain as much parity with server API as possible.

It would be good If someone having good experience in ruby data structures to answer this.
@PrajaktaPurohit Would you like to answer ?

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/issues/2511 @marcparadise created an issue to track this for sometime in the future. We currently estimate this to take anywhere between a week to a sprint for a new dev on the server team to be able to dig into and fix.

**Review by marcparadise — APPROVED** [review]

**Pull request merged**
