### PR TITLE
Add external_authentication_uid to actors endpoint for querying

### PR DESCRIPTION
**Pull request by kmacgugan**

### CODE REVIEW

**Comment by stevendanna** [comment]
Some minor nits:

- This prefers the email parameter over the external_auth_uid, while the Chef Server implementation is the other way around: https://github.com/chef/chef-server/pull/852
- The filtering code for email vs the new param is basically identical, maybe split it out into a function that takes the response and the field to filter by?

**Comment by srenatus** [comment]
@stevendanna I've updated the PR to address your concerns. :)

**Comment by stevendanna** [comment]
👍 Looks good to me.

**Comment by chefsalim** [comment]
👍

**Pull request merged**
