### PR TITLE
Update chef-zero.gemspec

### PR DESCRIPTION
**Pull request by rreyes**
updating hashie version because I get an error when trying to use it with the grape gem

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @rreyes

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by monfresh** [comment]
I updated hashie locally and all the tests passed, so it seems like this change can be made. It would be great to have hashie updated. Thanks!

**Comment by xeron** [comment]
Related PR #164

**Comment by jkeiser** [comment]
@rreyes sorry, I hadn't seen this one yet, but I've made the update and released chef-zero 4.3.1, which addresses this issue.

**Pull request closed without merging**
