### PR TITLE
Remove dependency on chef

### PR DESCRIPTION
**Pull request by terceiro**
I am updating chef-zero in Debian, and when building the package in a clean environment (with no chef, and only the dependencies that are declared in the gemspec installed), tests fail. This PR has two commits that fix the issue for me.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @terceiro

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by terceiro** [comment]
I see the CI failure, already reproduced it locally; will fix.

**Comment by randomcamel** [comment]
@terceiro I see the problem you're solving, but why is the solution to change the code rather than add `chef` as a dependency in the gemspec?

**Comment by terceiro** [comment]
@randomcamel because 1) circular dependencies will usually cause problems at some point and 2) the dependency on chef was explicitly removed a while ago (but not quite)

as an example of problems with circular dependencies: I maintain chef and most of its dependencies in Debian, and needing chef to build chef-zero, and needing chef-zero to build chef (because in both cases the test suites are executed) _is_ a problem. Because we always run test suites during Debian builds, I already lost count of bugs/patches I submitted to Ruby libraries and programs due to build failures in Debian, so I think everyone wins if that stays being possible.

**Comment by jkeiser** [comment]
Removing `Chef::` references is generally good. This was designed to not depend on it, since chef was supposed to depend on *it*.

I don't think Chef::Version and Gem::Version are any different.

Are these really the only deps that have crept in?

**Comment by jkeiser** [comment]
:+1: on it, BTW.

**Comment by randomcamel** [comment]
:+1:

**Pull request merged**
